# Generated by Django 2.0.5 on 2018-06-05 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StudentModel',
            new_name='Student',
        ),
    ]
